import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>LukeJo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Luke Johnson</h1>

        <p className={styles.description}>GraphQL, React, Node.js Engineer</p>

        <div className={styles.grid}>
          <a href="/resume.pdf" className={styles.card}>
            <h2>Resumé &rarr;</h2>
            <p>
              Check out my resume and see if I&apos;d be a good fit for your
              team.
            </p>
          </a>

          <a href="https://github.com/lukejo-io" className={styles.card}>
            <h2>GitHub &rarr;</h2>
            <p>
              See some of my code first-hand. It's mostly just old school
              projects and personal websites.
            </p>
          </a>

          <a href="https://twitter.com/lukejo_io" className={styles.card}>
            <h2>Twitter &rarr;</h2>
            <p>Follow me on Twitter and find out what I like talking about.</p>
          </a>

          <a
            href="https://www.linkedin.com/in/luke-j-281646223"
            className={styles.card}
          >
            <h2>LinkedIn &rarr;</h2>
            <p>
              Let&apos;s connect and we can see how I can help you accomplish
              your goals.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with Next.js
        </a>
      </footer>
    </div>
  );
};

export default Home;
